import type { EmailItem, User } from '../types';

export const DEFAULT_USER: User = {
  id: 'user_oliver_1',
  name: 'Oliver Brown',
  email: 'oliver.brown@domain.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const INITIAL_SCHEDULED_EMAILS: EmailItem[] = [
  {
    id: 'sch_1',
    to: 'john.smith@acme.corp',
    toName: 'John Smith',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: 'Meeting follow-up - Scheduled',
    snippet: 'Hi John, just wanted to follow up on our meeting yesterday regarding the enterprise AI outbound workflows...',
    body: `<p>Hi John,</p><p>Just wanted to follow up on our meeting yesterday regarding the enterprise AI outbound workflows. We'd love to schedule a quick 15-minute walkthrough of the ReachInbox AI cold outreach engine.</p><p>Let me know if tomorrow at 2 PM works for you!</p><p>Best regards,<br/>Oliver Brown</p>`,
    status: 'scheduled',
    scheduledTime: 'Tue 9:15:12 AM',
    timestamp: Date.now() + 86400000,
    starred: false,
    delaySeconds: 15,
    hourlyLimit: 50,
  },
  {
    id: 'sch_2',
    to: 'olive.miller@growthlabs.co',
    toName: 'Olive',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: "Ramit, great to meet you - you'll love it",
    snippet: "Hi Olive, just wanted to follow up on our meeting and share the latest performance metrics on cold email campaigns...",
    body: `<p>Hi Olive,</p><p>Great connecting! Ramit mentioned we should sync on how ReachInbox can automate your prospecting and verification pipeline.</p><p>Looking forward to speaking soon.</p><p>Cheers,<br/>Oliver</p>`,
    status: 'scheduled',
    scheduledTime: 'Thu 8:15:12 PM',
    timestamp: Date.now() + 172800000,
    starred: false,
    delaySeconds: 20,
    hourlyLimit: 60,
  },
  {
    id: 'sch_3',
    to: 'alex.morgan@venturepeak.com',
    toName: 'Alex Morgan',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: 'Scaling your SDR team with AI prospecting',
    snippet: 'Hey Alex, saw your recent announcement about expanding the sales org. Here is how ReachInbox saves 20 hrs/week...',
    body: `<p>Hey Alex,</p><p>Saw your recent announcement about expanding the sales org. ReachInbox automates lead discovery, enrichment, and personalized sequencing in one click.</p><p>Would love to share a 2-minute demo.</p><p>Best,<br/>Oliver</p>`,
    status: 'scheduled',
    scheduledTime: 'Fri 11:30:00 AM',
    timestamp: Date.now() + 259200000,
    starred: true,
    delaySeconds: 10,
    hourlyLimit: 40,
  },
  {
    id: 'sch_4',
    to: 'david.kim@nexusmedia.io',
    toName: 'David Kim',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: 'AI-driven cold outreach benchmarks for Q4',
    snippet: 'Hi David, wanted to share our Q4 benchmark report on 500k+ outbound emails delivered with 98% inbox deliverability...',
    body: `<p>Hi David,</p><p>Here is the Q4 outbound deliverability benchmark report we discussed.</p><p>Warmly,<br/>Oliver</p>`,
    status: 'scheduled',
    scheduledTime: 'Mon 10:00:00 AM',
    timestamp: Date.now() + 345600000,
    starred: false,
    delaySeconds: 30,
    hourlyLimit: 75,
  }
];

export const INITIAL_SENT_EMAILS: EmailItem[] = [
  {
    id: 'sent_1',
    to: 'sarah.wilson@hyperion.io',
    toName: 'Sarah Wilson',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: 'Re: Project Update',
    snippet: 'Thanks for the update, Sarah. Looks good! We are ready to roll out the new campaign sequences across all domains.',
    body: `<p>Thanks for the update, Sarah. Looks good!</p><p>We are ready to roll out the new campaign sequences across all domains starting tomorrow morning.</p><p>Let me know if any questions arise.</p><p>Best regards,<br/>Oliver</p>`,
    status: 'sent',
    sentTime: 'Nov 3, 2:45 PM',
    timestamp: Date.now() - 3600000,
    starred: false,
  },
  {
    id: 'sent_2',
    to: 'support@reachinbox.ai',
    toName: 'Support',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: 'Issue with login',
    snippet: 'I am having trouble logging in to the dashboard via OAuth redirect, could you please verify the API token callback?',
    body: `<p>Hi Support team,</p><p>I am having trouble logging in to the dashboard via OAuth redirect, could you please verify the API token callback?</p><p>Thanks,<br/>Oliver</p>`,
    status: 'sent',
    sentTime: 'Nov 3, 1:12 PM',
    timestamp: Date.now() - 7200000,
    starred: false,
  },
  {
    id: 'sent_3',
    to: 'oliver.brown@domain.io',
    toName: 'Oliver',
    from: 'sender@example.com',
    fromName: 'Amanda Clark',
    subject: 'Oliver, hello there! | MJWYT44 BM#52W01',
    snippet: "Hey Oliver, You've just RECEIVED something - Extremely Exclusive—Only 4 Spots Worldwide Per Year...",
    body: `Hey Oliver,

You've just RECEIVED something`,
    bannerHighlight: {
      title: 'Extremely Exclusive—Only 4 Spots Worldwide Per Year | $25,000 investment',
      description: 'To explore securing your private transformation, simply reply right now with "FLY OUT FIX" .',
    },
    status: 'sent',
    sentTime: 'Nov 3, 10:23 AM',
    timestamp: Date.now() - 86400000,
    starred: true,
    attachments: [
      {
        name: 'Tennis_Coach_Profile.png',
        size: '1.2 MB',
        url: '/tennis_coach_profile.jpg',
      },
      {
        name: 'Tennis_Coach_Profile2.png',
        size: '1.2 MB',
        url: '/tennis_coach_profile2.jpg',
      }
    ]
  },
  {
    id: 'sent_4',
    to: 'elena.rostova@cloudscale.net',
    toName: 'Elena Rostova',
    from: 'oliver.brown@domain.io',
    fromName: 'Oliver Brown',
    subject: 'Automating high-intent lead enrichment',
    snippet: 'Hi Elena, ReachInbox automatically enriches verified B2B contacts with social signals and intent data...',
    body: `<p>Hi Elena,</p><p>ReachInbox automatically enriches verified B2B contacts with social signals and intent data so your email copy is 100% personalized.</p><p>Best,<br/>Oliver</p>`,
    status: 'sent',
    sentTime: 'Nov 2, 4:15 PM',
    timestamp: Date.now() - 172800000,
    starred: false,
  }
];
